app:
  verAplic: 'MS_DFE_${app_version}'
  secrets:
    path: ${SECRETS_PATH:/run/secrets/}
  database:
    payments:
      name: payments_methods_db
      host: ${API_DATABASE_HOST:localhost}
      port: ${API_DATABASE_PORT:1433}
      username: ${API_DATABASE_USER}
      password: ${API_DATABASE_PWD}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: '/api-payment-methods/apm/manage'
      exposure:
        include: health,metrics,info,prometheus
      path-mapping:
        health: healthcheck
resilience4j:
  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
      shared:
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 30
        slidingWindowSize: 100
        waitDurationInOpenState: 45s
    instances:
      nf3edb:
        baseConfig: default
  retry:
    configs:
      default:
        maxRetryAttempts: 4
        waitDuration: 1000
    instances:
      nf3edb:
        baseConfig: default
server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: api-payment-methods-${region}
#  cache:
#    jcache:
#      config: classpath:ehcache.xml
  r2dbc:
    initialization-mode: always
    pool:
      initial-size: ${API_DATABASE_POOL_INITIAL:50}
      max-size: ${API_DATABASE_POOL_MAX:128}
      enabled: true
  rsocket:
    server:
      address: 0.0.0.0
      port: ${RSOCKET_SERVER_PORT:7000}
      transport: tcp
