version: '3.1'

services:

#  db:
#    image: microsoft/mssql-server-linux:latest
#    expose:
#      - 1433
#    ports:
#      - 1433:1433
#    networks:
#      - icorrea_net
#    environment:
#      - ACCEPT_EULA=Y
#      - MSSQL_PID=Standard
#      - SA_PASSWORD=senha123
#      - MSSQL_AGENT_ENABLED=true
#    volumes:
#      - ~/srv/mssql/cfopsdb:/var/opt/mssql

    db:
      image: icorrea/postgresql:11.7-alpine3.11
      environment:
        POSTGRES_PASSWORD: senha123
        POSTGRES_USER: userncms
        POSTGRES_DB: ncmsdb
      networks:
        - icorrea_net
      volumes:
        - ~/svr/postgresql/api-ncms-data:/var/lib/postgresql/data
      ports:
        - 5432:5432

    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "italiviocorrea@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "senha123"
      ports:
        - 8181:80
      depends_on:
        - db
      networks:
        - icorrea_net

networks:
  icorrea_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.0.0/16

