spring:
  application:
    name: k9999-api-mdfes-hadoop
  datasource:
    driver-class-name: ${DS_DRIVER}
    url: ${DS_URI}
    username: ${DS_USER}
    password: ${DS_PWD}
    hikari:
      maximum-pool-size: ${DS_POOL_MAX:64}
      minimum-idle: ${DS_POOL_MIN:10}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: '/k9999/apm/manage'
      exposure:
        include: 'health,metrics,info,prometheus'
      path-mapping:
        health: healthcheck
resilience4j:
  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 60
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
      shared:
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 30
        slidingWindowSize: 100
        waitDurationInOpenState: 45s
    instances:
      mdfesdb:
        baseConfig: default
  retry:
    configs:
      default:
        maxRetryAttempts: 4
        waitDuration: 1000
    instances:
      mdfesdb:
        baseConfig: default
springdoc:
  swagger-ui:
    path: /api/v1/docs/swagger-ui.html
