apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-payment-methods-server
  name: api-payment-methods-server
  namespace: nf3e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-payment-methods-server
  template:
    metadata:
      labels:
        app: api-payment-methods-server
    spec:
      containers:
      - name: api-payment-methods-server
        image: icorrea/api-payment-methods-server:0.0.1
        env:
          - name: region
            value: "dev"
        ports:
          - containerPort: 7000
        readinessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api-payment-methods-hdl-service
  namespace: nf3e
spec:
  clusterIP: None
  selector:
    app: api-payment-methods-server
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
